Repository elice-promotion-site-team/elice-promotion-site-backend, pull requests merged in 2022-06, with the labels that each got.

#11 from Dev to Master
  .DS_Store
  package-lock.json
  package.json
  src/customType/express.d.ts
  src/db/index.ts
  src/db/models/chat-model.ts
  src/db/models/guestbook-model.ts
  src/db/schemas/chat-schema.ts
  src/db/schemas/guestbook-schema.ts
  src/middlewares/error-handler.ts
  src/middlewares/index.ts
  src/middlewares/login-required.ts
  src/routes/chat-router.ts
  src/routes/guestbook-router.ts
  src/routes/index.ts
  src/server.ts
  src/services/chat-service.ts
  src/services/guestbook-service.ts
  src/services/index.ts
  src/socket.ts
  src/static/css/index.css
  src/static/index.html
Labels: enhancement

#16 유저 및 소셜 로그인 기능
  .prettierignore
  package-lock.json
  package.json
  src/db/index.ts
  src/db/schemas/user.ts
  src/middlewares/error-handler.ts
  src/middlewares/get-user-from-jwt.ts
  src/middlewares/index.ts
  src/passport/index.ts
  src/passport/strategies/google.ts
  src/passport/strategies/jwt.ts
  src/routes/auth.ts
  src/routes/index.ts
  src/routes/user.ts
  src/server.ts
  src/services/index.ts
  src/services/user.ts
  src/utils/jwt.ts
Labels: bug, enhancement

#18 퀴즈 기능
  package.json
  src/db/index.ts
  src/db/models/chat-model.ts
  src/db/models/quiz-model.ts
  src/db/schemas/chat.ts
  src/db/schemas/quiz.ts
  src/routes/chat.ts
  src/routes/index.ts
  src/routes/quiz.ts
  src/server.ts
  src/services/chat.ts
  src/services/index.ts
  src/services/quiz.ts
  src/socket.ts
Labels: enhancement

#23 수정 - 아키텍처 수정
  src/models/index.ts
  src/models/schemas/chat-schema.ts
  src/models/schemas/index.ts
  src/models/will-delete/chat-model.ts
  src/models/will-delete/quiz-model.ts
  src/routes/api.ts
  src/routes/api/chat.ts
  src/routes/api/index.ts
  src/routes/api/quiz.ts
  src/routes/index.ts
  src/server.ts
  src/services/chat.ts
  src/services/quiz.ts
Labels: enhancement

#24 방명록 사용자 정보 연동 기능
  src/models/schemas/guestbook.ts
  src/models/schemas/user.ts
  src/passport/strategies/google.ts
  src/routes/auth.ts
  src/services/guestbook.ts
  src/services/user.ts
  src/utils/jwt.ts
Labels: enhancement

#30 추가 - 퀴즈 내용
  package-lock.json
  src/models/schemas/quiz.ts
  src/services/quiz.ts
Labels: enhancement

#31 수정 - quiz schema에서 quizName 속성 삭제
  src/models/schemas/quiz.ts
  src/services/quiz.ts
Labels: documentation

#32 수정 - console.log 삭제
  src/routes/api/chat.ts
  src/services/user.ts
  src/socket.ts
Labels: documentation
